name: 'Build discussion'
description: 'Creates a GitHub discussion'
author: 'Noelia Ruiz Martínez'

# Define your inputs here.
inputs:
  repository:
    description:
      'Repository name with owner. For example, nvdaes/build-discussion'
    required: true
    default: ${{ github.repository }}
  token:
    description: 'GitHub token'
    required: true
    default: ${{ github.token }}
  category-position:
    description:
      'Position of the category for the discussion to be created, starting with
      1 for the first available category'
    required: true
    default: '1'
  title:
    description: 'Discussion title'
    required: true
    default: 'Discussion created with Build discussion action'
  body:
    description: 'Discussion body'
    required: true
    default: 'This is the discussion body'

# Define your outputs here.
outputs:
  discussion-id:
    description: 'ID of the created discussion'
    value: ${{ steps.create-discussion.outputs.discussion-id }}
  discussion-url:
    description: 'URL of the created discussion'
    value: ${{ steps.create-discussion.outputs.discussion-url }}
  discussion-number:
    description: 'Number of the created discussion'
    value: ${{ steps.create-discussion.outputs.discussion-number }}

runs:
  using: composite
  steps:
    - name: Create GitHub Discussion
      id: create-discussion
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        REPOSITORY: ${{ inputs.repository }}
        CATEGORY_POSITION: ${{ inputs.category-position }}
        TITLE: ${{ inputs.title }}
        BODY: ${{ inputs.body }}
      run: ${{ github.action_path }}/scripts/create-discussion.sh
