name: 'Build  discussion'
description: 'Creates a GitHub discussion'
author: 'Noelia Ruiz Martínez'

# Define your inputs here.
inputs:
  repository:
    description: 'Repository name with owner. For example, nvdaes/build-discussion'
    required: true
    default: ${{ github.repository }}
  token:
    description: 'GitHub token'
    required: true
    default: ${{ github.token }}
  category-position:
    description: 'Position of the category of the discussion to be created, starting with 1 for the first available category'
    required: true
    default: '1'

# Define your outputs here.
outputs:
  discussion-id:
    description: 'ID of the created discussion'
  discussion-url:
    description: 'URL of the created discussion'

runs:
  using: node20
  main: dist/index.js
